export enum PLATFORM {
  ANDROID = "android",
  IOS = "ios",
  H5 = "h5",
  MP_WEIXIN = "mp-weixin",
  MP_ALIPAY = "mp-alipay",
  MP_BAIDU = "mp-baidu",
  MP_TOUTIAO = "mp-toutiao",
  MP_LARK = "mp-lark",
  MP_QQ = "mp-qq",
  MP_KUAISHOU = "mp-kuaishou",
  MP_JD = "mp-jd",
  MP_360 = "mp-360",
  MP_XHS = "mp-xhs",
  MP_QUICKAPP_UNION = "quickapp-union",
  MP_QUICKAPP_HUAWEI = "quickapp-huawei",
}
export const allPlatforms = [
  PLATFORM.ANDROID,
  PLATFORM.IOS,
  PLATFORM.H5,
  PLATFORM.MP_WEIXIN,
  PLATFORM.MP_ALIPAY,
  PLATFORM.MP_BAIDU,
  PLATFORM.MP_TOUTIAO,
  PLATFORM.MP_LARK,
  PLATFORM.MP_QQ,
  PLATFORM.MP_KUAISHOU,
  PLATFORM.MP_JD,
  PLATFORM.MP_360,
  PLATFORM.MP_XHS,
  PLATFORM.MP_QUICKAPP_UNION,
  PLATFORM.MP_QUICKAPP_HUAWEI,
];
